apiVersion: v1
kind: Service
metadata:
  name: url-shorten-service
  namespace: url-shortener
  labels:
    app: url-shorten
spec:
  selector:
    matchLabels: 
      app: url-shorten
  ports:
    type: NodePort
    ports:
      - port: 80
        nodePort: 80
        name: http
